### PR TITLE
Fix request body serializing with FORMAT clause

### LINKED ISSUE #25: The last blank is trimed，so how to fix this error
error:
Error: Unknown format CSV1550220733

Code

> let statement =  'INSERT INTO testTable FORMAT CSV ';
>         let csvStream = fs.createReadStream (‘csv.csv’);
>         let clickhouseStream = ch.query (statement, {inputFormat: 'CSV'});
>         csvStream.pipe (clickhouseStream);
>         clickhouseStream.on('end',function(){
>             ac(file_name+'->success');
>         });
>         clickhouseStream.on ('error', function (err) {
>            console.log(err);
>            ac(file_name+'->false');
>         });
> 

csv file

`1550220733,22222,33333`

### PR DESCRIPTION
**Pull request by nezed**
Fixes #25 
Relates to #36

### CODE REVIEW

File: test/05-insert.js [hunk 1]
```diff
@@ -327,6 +327,59 @@ describe ("insert data", function () {
...
+
+					done ();
+
+				});
+			});
+			stream.write('0,0,\\N,"1970-01-02 00:00:00"\n1,1.5,"1","2050-01-01 00:00:00"')
+			stream.end ();
+		});
+
+		it ("select data with FORMAT clause", function () {
```
Comment (nezed) [inline test/05-insert.js]: Perhaps it makes sense to put in a separate test
